FROM python:3.13-slim

EXPOSE 9191

ENV PYTHONUNBUFFERED=1

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# اینجا مسیر فایلی که اگر اجرا بشه سرور شروع به گوش دادن خواهد کرد رو قرار بدید.
CMD ["python", "./server_online.py"] 